#include "p3ui.h"

#include <imgui.h>
#include <p3/widgets/InputText.h>

namespace p3::python {

void ArgumentParser<InputText>::operator()(py::kwargs const& kwargs, InputText& input_text)
{
    ArgumentParser<Node>()(kwargs, input_text);
    assign(kwargs, "hint", input_text, &InputText::set_hint);
    assign(kwargs, "multi_line", input_text, &InputText::set_multi_line);
    assign(kwargs, "on_change", input_text, &InputText::set_on_change);
}

void Definition<InputText>::apply(py::module& module)
{
    py::class_<InputText, Node, std::shared_ptr<InputText>> input(module, "InputText");

    input.def(py::init<>([](std::size_t size, py::kwargs kwargs) {
        auto input = std::make_shared<InputText>(size);
        ArgumentParser<InputText>()(kwargs, *input);
        return input;
    }),
        py::kw_only(), py::arg("size") = 16);

    def_signal_property(input, "on_change", &InputText::on_change, &InputText::set_on_change);
    def_property(input, "value", &InputText::value, &InputText::set_value);
    def_property(input, "multi_line", &InputText::multi_line, &InputText::set_multi_line);
    py::enum_<ImGuiKey_>(module, "Key")
        .value("None", ImGuiKey_None)
        .value("Tab", ImGuiKey_Tab)
        .value("LeftArrow", ImGuiKey_LeftArrow)
        .value("RightArrow", ImGuiKey_RightArrow)
        .value("UpArrow", ImGuiKey_UpArrow)
        .value("DownArrow", ImGuiKey_DownArrow)
        .value("PageUp", ImGuiKey_PageUp)
        .value("PageDown", ImGuiKey_PageDown)
        .value("Home", ImGuiKey_Home)
        .value("End", ImGuiKey_End)
        .value("Insert", ImGuiKey_Insert)
        .value("Delete", ImGuiKey_Delete)
        .value("Backspace", ImGuiKey_Backspace)
        .value("Space", ImGuiKey_Space)
        .value("Enter", ImGuiKey_Enter)
        .value("Escape", ImGuiKey_Escape)
        .value("LeftCtrl", ImGuiKey_LeftCtrl)
        .value("LeftShift", ImGuiKey_LeftShift)
        .value("LeftAlt", ImGuiKey_LeftAlt)
        .value("LeftSuper", ImGuiKey_LeftSuper)
        .value("RightCtrl", ImGuiKey_RightCtrl)
        .value("RightShift", ImGuiKey_RightShift)
        .value("RightAlt", ImGuiKey_RightAlt)
        .value("RightSuper", ImGuiKey_RightSuper)
        .value("Menu", ImGuiKey_Menu)
        .value("0", ImGuiKey_0)
        .value("1", ImGuiKey_1)
        .value("2", ImGuiKey_2)
        .value("3", ImGuiKey_3)
        .value("4", ImGuiKey_4)
        .value("5", ImGuiKey_5)
        .value("6", ImGuiKey_6)
        .value("7", ImGuiKey_7)
        .value("8", ImGuiKey_8)
        .value("9", ImGuiKey_9)
        .value("A", ImGuiKey_A)
        .value("B", ImGuiKey_B)
        .value("C", ImGuiKey_C)
        .value("D", ImGuiKey_D)
        .value("E", ImGuiKey_E)
        .value("F", ImGuiKey_F)
        .value("G", ImGuiKey_G)
        .value("H", ImGuiKey_H)
        .value("I", ImGuiKey_I)
        .value("J", ImGuiKey_J)
        .value("K", ImGuiKey_K)
        .value("L", ImGuiKey_L)
        .value("M", ImGuiKey_M)
        .value("N", ImGuiKey_N)
        .value("O", ImGuiKey_O)
        .value("P", ImGuiKey_P)
        .value("Q", ImGuiKey_Q)
        .value("R", ImGuiKey_R)
        .value("S", ImGuiKey_S)
        .value("T", ImGuiKey_T)
        .value("U", ImGuiKey_U)
        .value("V", ImGuiKey_V)
        .value("W", ImGuiKey_W)
        .value("X", ImGuiKey_X)
        .value("Y", ImGuiKey_Y)
        .value("Z", ImGuiKey_Z)
        .value("F1", ImGuiKey_F1)
        .value("F2", ImGuiKey_F2)
        .value("F3", ImGuiKey_F3)
        .value("F4", ImGuiKey_F4)
        .value("F5", ImGuiKey_F5)
        .value("F6", ImGuiKey_F6)
        .value("F7", ImGuiKey_F7)
        .value("F8", ImGuiKey_F8)
        .value("F9", ImGuiKey_F9)
        .value("F10", ImGuiKey_F10)
        .value("F11", ImGuiKey_F11)
        .value("F12", ImGuiKey_F12)
        .value("Apostrophe", ImGuiKey_Apostrophe)
        .value("Comma", ImGuiKey_Comma)
        .value("Minus", ImGuiKey_Minus)
        .value("Period", ImGuiKey_Period)
        .value("Slash", ImGuiKey_Slash)
        .value("Semicolon", ImGuiKey_Semicolon)
        .value("Equal", ImGuiKey_Equal)
        .value("LeftBracket", ImGuiKey_LeftBracket)
        .value("Backslash", ImGuiKey_Backslash)
        .value("RightBracket", ImGuiKey_RightBracket)
        .value("GraveAccent", ImGuiKey_GraveAccent)
        .value("CapsLock", ImGuiKey_CapsLock)
        .value("ScrollLock", ImGuiKey_ScrollLock)
        .value("NumLock", ImGuiKey_NumLock)
        .value("PrintScreen", ImGuiKey_PrintScreen)
        .value("Pause", ImGuiKey_Pause)
        .value("Keypad0", ImGuiKey_Keypad0)
        .value("Keypad1", ImGuiKey_Keypad1)
        .value("Keypad2", ImGuiKey_Keypad2)
        .value("Keypad3", ImGuiKey_Keypad3)
        .value("Keypad4", ImGuiKey_Keypad4)
        .value("Keypad5", ImGuiKey_Keypad5)
        .value("Keypad6", ImGuiKey_Keypad6)
        .value("Keypad7", ImGuiKey_Keypad7)
        .value("Keypad8", ImGuiKey_Keypad8)
        .value("Keypad9", ImGuiKey_Keypad9)
        .value("KeypadDecimal", ImGuiKey_KeypadDecimal)
        .value("KeypadDivide", ImGuiKey_KeypadDivide)
        .value("KeypadMultiply", ImGuiKey_KeypadMultiply)
        .value("KeypadSubtract", ImGuiKey_KeypadSubtract)
        .value("KeypadAdd", ImGuiKey_KeypadAdd)
        .value("KeypadEnter", ImGuiKey_KeypadEnter)
        .value("KeypadEqual", ImGuiKey_KeypadEqual)
        .value("GamepadStart", ImGuiKey_GamepadStart)
        .value("GamepadBack", ImGuiKey_GamepadBack)
        .value("GamepadFaceUp", ImGuiKey_GamepadFaceUp)
        .value("GamepadFaceDown", ImGuiKey_GamepadFaceDown)
        .value("GamepadFaceLeft", ImGuiKey_GamepadFaceLeft)
        .value("GamepadFaceRight", ImGuiKey_GamepadFaceRight)
        .value("GamepadDpadUp", ImGuiKey_GamepadDpadUp)
        .value("GamepadDpadDown", ImGuiKey_GamepadDpadDown)
        .value("GamepadDpadLeft", ImGuiKey_GamepadDpadLeft)
        .value("GamepadDpadRight", ImGuiKey_GamepadDpadRight)
        .value("GamepadL1", ImGuiKey_GamepadL1)
        .value("GamepadR1", ImGuiKey_GamepadR1)
        .value("GamepadL2", ImGuiKey_GamepadL2)
        .value("GamepadR2", ImGuiKey_GamepadR2)
        .value("GamepadL3", ImGuiKey_GamepadL3)
        .value("GamepadR3", ImGuiKey_GamepadR3)
        .value("GamepadLStickUp", ImGuiKey_GamepadLStickUp)
        .value("GamepadLStickDown", ImGuiKey_GamepadLStickDown)
        .value("GamepadLStickLeft", ImGuiKey_GamepadLStickLeft)
        .value("GamepadLStickRight", ImGuiKey_GamepadLStickRight)
        .value("GamepadRStickUp", ImGuiKey_GamepadRStickUp)
        .value("GamepadRStickDown", ImGuiKey_GamepadRStickDown)
        .value("GamepadRStickLeft", ImGuiKey_GamepadRStickLeft)
        .value("GamepadRStickRight", ImGuiKey_GamepadRStickRight)
        .value("ModCtrl", ImGuiKey_ModCtrl)
        .value("ModShift", ImGuiKey_ModShift)
        .value("ModAlt", ImGuiKey_ModAlt)
        .value("ModSuper", ImGuiKey_ModSuper);
}

}
