name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.8"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Prepare
      run: python -m pip install --no-cache-dir --upgrade wheel setuptools

    - name: Build
      run:  python -m pip wheel . -w whl --no-deps
