name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - build1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.8"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .
