name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - build1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.7", "3.8", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools
      run: python -m pip install --no-cache-dir --upgrade wheel setuptools twine

    - name: Build and install
      run:  python -m pip wheel . --use-feature=in-tree-build -w whl --no-deps
 #     run: pip install --verbose --use-feature=in-tree-build .

    - name: Publish to (Test-) PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        twine upload --repository testpypi --skip-existing whl\*
