name: Build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.7", "3.8", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools
      run: python -m pip install --no-cache-dir --upgrade wheel setuptools twine

    - name: Build and install
      run:  python -m pip wheel . --use-feature=in-tree-build -w whl --no-deps

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing whl\*
